### ISSUE TITLE
Project is broken

### ISSUE THREAD

**Issue by fabiensanglard** [czak/minimal-android-project#2]
Just tried after installing Gradle 2.1 but I get an error trying to build:

```
% ~/Downloads/gradle-2.2.1/bin/gradle installDebug

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '19.0.2'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by docbrown** [comment]
Gradle 2.1 doesn't support Java 19. Try using the latest version of Gradle instead.

**Comment by czak** [comment]
I've now updated the project to the latest Android Gradle plugin (v8.5.2).
This requires Gradle 8.7 or higher, according to [the plugin docs](https://developer.android.com/build/releases/gradle-plugin#updating-gradle).

I've successfully built and installed the project with Gradle 8.10 on OpenJDK 17.0.12 and OpenJDK 22.0.2.

I hope it works for you as well. Thanks!
